# Generated by Django 5.0.4 on 2024-04-07 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_clients_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='updated_by',
            new_name='updated_at',
        ),
    ]
